### ISSUE TITLE
Add support for Factorio 0.18

### ISSUE THREAD

**Issue by Vescatur** [KirkMcDonald/factorio-tools#13]
I tried to running factoriocalc 0.3 on factorio 0.18 but I unfortunately get a crash. I am using the windows build 0.3. 

![image](https://user-images.githubusercontent.com/13928590/78386436-d9c4d880-75dd-11ea-8cf3-19689566d81f.png)

I have tried running it with 0.17 and it does work there. Would you be able to add support for 0.18?

I know the recipes havn't changed in 0.18 but I would like to use it with a mod.

**Comment by RustyBlade64** [comment]
The problem is fixed in #14. You'll either have to wait for @KirkMcDonald to make a new release or you can try building my pull request branch from source for yourself according to the description in the README.

**Comment by Vescatur** [comment]
Thank you @RustyBlade64 for the commit. I have tried following the read me but I couldn't get my C compiler to work. Would you be able to build it? It would mean the world to me.

**Comment by RustyBlade64** [comment]
I'm not on Windows, so I can't create any Windows binaries.

**Comment by hhrhhr** [comment]
@RustyBlade64 — https://github.com/golang/go/wiki/WindowsCrossCompiling

**Comment by hhrhhr** [comment]
@Vescatur , If you wish, you can try my [factorio-tools build](https://bitbucket.org/hhrhhr/factorio-tools-lua), which was done using the Tiny C Compiler and completely rewritten in Lua (instead of Go). All issues regarding 0.18.xx are also fixed.
