### ISSUE TITLE
Setting Preferred Electronic Machine

### ISSUE THREAD

**Issue by HendrikDanker** [KirkMcDonald/factorio-tools#6]
I used this for Bob's Pack, trying to get ratios for making Electronic Circuits.

However the calculator only lets you select which Assembly Machine is preferred, but not which Electronic Assembly Machine. Which means it defaulted to the Tech 3 variant. 

Is there a way to set this to a lower level?

**Comment by KirkMcDonald** [comment]
There is not. I have created an issue for this at KirkMcDonald/kirkmcdonald.github.io#130. It's really more an issue for the calculator proper than for these tools.
